---
- name: ensure flyway is downloaded
  stat: path="{{ flyway.download_path }}"
  register: st

- name: download flyway
  get_url:
    url: "{{ flyway.download_url }}"
    dest: "{{ flyway.download_path }}"
    mode: 0644
  when:
    st.exists is not defined

- name: create flyway installation directory
  file: name="{{ flyway.directory }}" state=directory owner=vagrant group=vagrant

- name: install flyway
  shell: tar xf "{{ flyway.download_path }}" -C "{{ flyway.directory }}" --strip-components 1
  become_user: vagrant
